# Generated by Django 5.2.3 on 2025-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='date',
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
