# Generated by Django 5.2.3 on 2025-08-11 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialtransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='constructionmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
